title: "ProductReviews Pro"
description: "Honest product reviews and recommendations to help you make informed buying decisions"
url: "https://duke3c.github.io"
baseurl: "/test"

# Author Information (Type-on-Strap specific)
author:
  name: "Your Name"
  email: "your.email@example.com"
  github: "yourusername"
  twitter: "yourusername"
  linkedin: "yourlinkedin"

# SEO Settings
lang: "en-US"
timezone: "America/New_York"  # Change to your timezone

# Analytics & Monetization
#google_analytics: "G-XXXXXXXXXX"  # Replace with your Google Analytics ID

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 6
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

# Type-on-Strap Theme Settings
remote_theme: sylhare/Type-on-Strap

# Theme Color Scheme
theme_color: "#2c3e50"  # Dark blue-gray for professional look
color_theme: auto  # auto, light, or dark

# Portfolio Settings (for showcasing different product categories)
portfolio: true
portfolio_title: "Product Categories"

# Navigation (Type-on-Strap specific)
navbar:
  - title: "Home"
    url: "/"
  - title: "Reviews"
    url: "/reviews/"
  - title: "Categories" 
    url: "/portfolio/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Footer
footer_text: "© 2025 ProductReviews Pro. All rights reserved."

# Collections for organizing content
collections:
  reviews:
    output: true
    permalink: /:collection/:name/
  categories:
    output: true
    permalink: /category/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
      show_sidebar: true
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"
      author: "Your Name"

# Affiliate Marketing Specific
affiliate_disclosure: "This site contains affiliate links. We may earn a commission if you purchase through these links at no extra cost to you."

# Site Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Reviews"
    url: "/reviews/"
  - title: "Categories"
    url: "/portfolio/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.md
